### ISSUE TITLE
Ctrl-C kills child processes immediately

### ISSUE THREAD

**Issue by ilyaluk** [tofuutils/tenv#255]
**Describe the bug**
Hitting Ctrl+C while tenv is running subcommand immediately exits the program without waiting for a cleanup.

**To Reproduce**
1. Have some long-running terraform command that includes remote state locking (locking is optional, but easiest for a showcase)
2. Ctrl+C

For example:
```hcl
// main.tf
terraform {
    backend "s3" {
        bucket = "tfstates"
        key    = "test.tfstate"
        region = "..."

        dynamodb_table = "tflocks"
    }
}

resource "time_sleep" "this" {
    create_duration = "10s"
}
```

Run `terraform apply` (through `tenv`) and hit Ctrl+C

```
<snip>
time_sleep.this: Creating...
^C
Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...

Stopping operation...
```

Process exits, leaving lock in DynamoDB and potentially losing some state.

**Expected behavior**
Graceful process termination

In the example above, could be tested with
```
$ ~/.tenv/Terraform/…/terraform apply
<snip>
time_sleep.this: Creating...
^CStopping operation...

Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...

╷
│ Error: execution halted
│
│
╵
╷
│ Error: execution halted
│
│
╵
╷
│ Error: Create time sleep error
│
│   with time_sleep.this,
│   on 1.tf line 11, in resource "time_sleep" "this":
│   11: resource "time_sleep" "this" {
│
│ Original Error: context canceled
╵
```

Process exits cleanly and unlocks the state

**Environment (please complete the following information):**
- OS: macOS
- tofuenv version: v3.2.2

**Additional context**

Probably related to #97

**Comment by dvaumoron** [comment]
strange, the two level of proxy should send a kill only on a second interrupt signal (see https://github.com/tofuutils/tenv/blob/main/versionmanager/proxy/light/light.go#L64 and https://github.com/tofuutils/tenv/blob/main/pkg/cmdproxy/proxy.go#L127)

**Comment by ilyaluk** [comment]
I have not debugged the issue yet, but maybe Ctrl-C delivers SIGINT to the whole process group, and tenv forwards second SIGINT to terraform, causing immediate exit? Terragrunt wait a bit before delivering interrupt, as I can see:

https://github.com/gruntwork-io/terragrunt/blob/58e2c20ed2c50b4bdc3c278a01bc447fab650d78/shell/run_shell_cmd.go#L36-L43

**Comment by creeder-uturn** [comment]
Can confirm also occurring for me - I believe this to be a pretty big deal as in its current state, you cannot Cntrl+C a Terraform/Tofu run without losing state (which has unfortunately happened to me multiple times in the last week due to troubleshooting/development work).

**Comment by dvaumoron** [comment]
Same OS ?

**Comment by creeder-uturn** [comment]
> Same OS ?

Correct, sorry I should have specified. MacOS. tenv 3.2.2

**Comment by dvaumoron** [comment]
I think using [Cmd.SysProcAttr.Setpgid](https://pkg.go.dev/syscall#SysProcAttr) should solve the issue, enabled/disabled with env var or flag could avoid side effect for user which did not .encounter it.

**Comment by ilyaluk** [comment]
Hey @dvaumoron, the issue still happens on latest main (same tf code):
```
$ strings $(which tenv) | grep TENV_DETACHED_PROXY | wc -l
       2
$ TENV_DETACHED_PROXY=true tf apply
<snip usual stuff>
  Enter a value: yes
^C%
$ # exits immediately, no output at all. Force-unlock, and just to verify old behavior:
$ TENV_DETACHED_PROXY=false tf apply
<snip usual stuff>
  Enter a value: yes

time_sleep.this: Creating...
^C
Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...

Stopping operation...

Two interrupts received. Exiting immediately. Note that data loss may have occurred.

```

On second look, with `TENV_DETACHED_PROXY=true` tf apply does not apply at all, maybe it does not receive "yes" stdin? When running with `-auto-approve`:
```
$ TENV_DETACHED_PROXY=true tf apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # time_sleep.this will be created
  + resource "time_sleep" "this" {
      + create_duration = "10s"
      + id              = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
time_sleep.this: Creating...
^C%
$ # exits immediately, no output at all
```

**Comment by dvaumoron** [comment]
Hi @ilyaluk 

You said you use the last main, did you mean you build it ? I havent tagged/released this work when done (and forgot since, my apologies)

now the v2.3.5 should contains this fix, keep me in touch if it did not solve the issue

**Comment by ilyaluk** [comment]
Hi @dvaumoron

Yeah, I built it from `main` with `go install github.com/tofuutils/tenv/v3/cmd/...@main` .

I think it would be same with the release though, let me check it.

**Comment by ilyaluk** [comment]
Huh, there's no 3.2.5 release built, you tagged it as [v2.3.5](https://github.com/tofuutils/tenv/releases/tag/v2.3.5)

**Comment by dvaumoron** [comment]
The tag is now correct, however there is still a build issue

**Comment by dvaumoron** [comment]
Hi @ilyaluk 

Can you test with v3.2.8 ?

**Comment by ilyaluk** [comment]
Hi @dvaumoron! The behavior is the same as I described in https://github.com/tofuutils/tenv/issues/255#issuecomment-2429256722: when `TENV_DETACHED_PROXY=true`, stdin is not passed to terraform process, and the process exits immediately on Ctrl+C, leaving lock. If false — the old behavior, getting `Two interrupts received` message.

**Comment by dvaumoron** [comment]
Hi @ilyaluk

Does `TENV_DETACHED_PROXY` work better with v3.2.9 ?

**Comment by ilyaluk** [comment]
Hey @dvaumoron, thanks for the fixes! Tried 3.2.9.

Now it looks like this:

```
$ TENV_DETACHED_PROXY=true ./terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # time_sleep.this will be created
  + resource "time_sleep" "this" {
      + create_duration = "10s"
      + id              = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes
^C
^C%
$
```

It does not receive any input (however, now it exits only on second Ctrl+C), I could guess that this is because the child process group does not control the terminal (https://stackoverflow.com/a/58919517). Let me send a quick fix for that.

Something like this should do the trick: https://github.com/snabb/tcxpgrp/blob/master/tcxpgrp.go#L21-L28

**Comment by ilyaluk** [comment]
It was actually way easier to fix :)

**Comment by creeder-uturn** [comment]
So is the recommendation for MacOS users to run tenv with `TENV_DETACHED_PROXY=true` to prevent this issue going forward? If so, is there any reason it shouldn't just be the default for Mac users to maintain functionality of Cntrl+C?

I'm not sure the implications of a detached proxy, honestly - it's probably a future issue but the documentation could probably go a long way to clarifying what that means and the implications and when you may want to use this.

**Comment by dvaumoron** [comment]
Making this default behaviour on macOS ? I am unsure, does it happens on all macOS or is it other factor that limit the impact of this bug ?

Moreover it's a work in progress, so breaking thing for all macOS users when some of them may not experience any issue seem counter productive to me.

**Comment by creeder-uturn** [comment]
> Moreover it's a work in progress
Understood, I think validating functionality first is definitely the way before rolling it out default!

> so breaking thing for all macOS users
Do you believe the detached proxy mode will break anything (provided #277 is merged, since I realized after posting that it is currently broken until that's merged)? I'm flying blind, as I said: I don't really know the implications of this setting beyond potentially fixing this issue.

> some of them may not experience any issue
I don't have the evidence for it, but I strongly suspect this issue exists for all Mac users, if not Linux and/or Windows users, too. I can certainly poll a few people on my team (mostly Mac) to have them explicitly test and confirm this - but I don't know what would be special on my environment to cause something like this to happen if it's not just happening for all Mac users.

@ilyaluk just in case shell is a factor, are you using zsh or bash? I'm using the newest gnu bash on homebrew (not the MacOS default bash).

**Comment by ilyaluk** [comment]
Hey @creeder-uturn,

I've tested this on bundled zsh (5.9), and now on bash from homebrew (5.2), original issue is reproducible in both cases, and fixed in current main.

**Comment by creeder-uturn** [comment]
> Hey @creeder-uturn,
> 
> I've tested this on bundled zsh (5.9), and now on bash from homebrew (5.2), original issue is reproducible in both cases, and fixed in current main.

To clarify, it's fixed when `TENV_DETACHED_PROXY=true` but it still happens when it's false, right?

Thanks for double checking the shell!

**Comment by ilyaluk** [comment]
> To clarify, it's fixed when TENV_DETACHED_PROXY=true but it still happens when it's false, right?

Yep, that's correct

**Comment by creeder-uturn** [comment]
@ilyaluk Thanks for the clarification, also I noticed you improved the documentation slightly, appreciated!

I was able to validate that the issue does not occur on Windows for one user, and it was occurring on three different user's MacOS machine as well. I feel reasonably confident that confirms this behavior on MacOS generally.

@dvaumoron is it possible to get a deploy release for the current fix on passing stdin? I would like to get my team all using the new version and setting this environment variable, as it's been quite a pain for some of us!

Given that the default behavior on MacOS is very broken (the issue, as described, is _still_ true even with the current fixes until you set an environment variable), I want to heavily advocate for this behavior becoming the new default. This is a pretty nasty bug to encounter for the first time - given that not only does it leave the state locked but it fails to save the state of anything in the current apply.

I understand there's a risk to rolling this behavior as the default unexpectedly as well, however - is there a path to validating/building comfort/checking for additional side effects with this as the default that I can assist in any way with? I want to help in any way I'm capable :)

**Comment by dvaumoron** [comment]
v3.2.10 incoming

**Comment by kittydoor** [comment]
The sigint duplication issue also exists on Linux (at least for me) on tenv v3.2.10.
The workaround of enabling `TENV_DETACHED_PROXY=true` is required to ensure the clean cancellation.

**Comment by kvendingoldo** [comment]
@dvaumoron Probably folks are right about the default behavior. If all of them set this variable as default, why can't we do the sae?

**Comment by dvaumoron** [comment]
ok, I will change the default behavior on non Windows system (we have a splitted build on this particular part, because Windows does not handle same OS feature)

**Comment by tspearconquest** [comment]
Changing this default has broken Jenkins builds leveraging tenv unless we set `TENV_DETACHED_PROXY=false`

It appears that having this defaulted to true requires a TTY, because when we run our container with tenv locally with an interactive terminal, there is no issue, but when we run it either in CI or locally without the `-it` flag to docker, then it gives `Failure during tofu call : fork/exec /usr/bin/tenv: inappropriate ioctl for device` ("tofu" can be any of the proxy binaries, as we have seen this with terraform as well since upgrading to 4.0.3)

Is it expected that setting this is now mandatory? Can tenv check for the presence of the `CI` environment variable as it is a commonly used variable to indicate when you are in a CI environment; and if set to true (`CI=true`), then fallback to the old behavior, in order to avoid this?

**Comment by tspearconquest** [comment]
#308 should hopefully fix this -- assuming that I'm correct in that CI=true is used across all of the big CI players.
