### ISSUE TITLE
Install mode "direct" doesn't work for Terragrunt

### ISSUE THREAD

**Issue by kodachimaru** [tofuutils/tenv#406]
**Describe the bug**
Install mode "direct" doesn't work for Terragrunt

**To Reproduce**
1. Start with a clean slate (no Tg versions installed)
2. Enable "direct" install mode for Tg (`TG_INSTALL_MODE=direct`)
3. Install any Tg version (`tenv tg install`)

```text
$ export TG_INSTALL_MODE=direct

$ tenv tg install 0.75.1
Installing Terragrunt 0.75.1
Downloading https://api.github.com/repos/gruntwork-io/terragrunt/releases/gruntwork-io/terragrunt/releases/download/v0.75.1/terragrunt_darwin_arm64
Downloading https://api.github.com/repos/gruntwork-io/terragrunt/releases/gruntwork-io/terragrunt/releases/download/v0.75.1/SHA256SUMS
Error: file sha256 checksum not found for current platform
```

**Expected behavior**
I would expect that "direct" mode would work for Tg installation, just like for Tf.
Would be great because "direct" mode prevents issues with GH API rate-limits, or having to maintain a GH token for using `tenv`.

**Environment (please complete the following information):**
- OS: MacOS 14.4
- tfenv version: latest (4.4.0)

**Comment by kvendingoldo** [comment]
I can confirm that I have the same behavior. Looks like it's a bug after the last changes
MacOS: 15.1
```
➜  /tmp export TG_INSTALL_MODE=direct
➜  /tmp tenv tg install
No version files found for Terragrunt, fallback to latest strategy
Fetching all releases information from https://api.github.com/repos/gruntwork-io/terragrunt/releases
Found compatible version remotely : 2025040801
Installing Terragrunt 2025040801
Downloading https://api.github.com/repos/gruntwork-io/terragrunt/releases/gruntwork-io/terragrunt/releases/download/v2025040801/terragrunt_darwin_arm64
Downloading https://api.github.com/repos/gruntwork-io/terragrunt/releases/gruntwork-io/terragrunt/releases/download/v2025040801/SHA256SUMS
Error: file sha256 checksum not found for current platform
```

**Comment by kvendingoldo** [comment]
@kodachimaru I released version 4.5.0; Please, check it

**Comment by dvaumoron** [comment]
The URL is not correct, TG_REMOTE="https://github.com" should fix this (see in [Advanced remote configuration](https://github.com/tofuutils/tenv?tab=readme-ov-file#advanced-remote-configuration))

**Comment by kodachimaru** [comment]
@kvendingoldo , I still can't see the 4.5.0 release

https://github.com/tofuutils/tenv/releases

Has it really been released?

**Comment by kvendingoldo** [comment]
@kodachimaru @Nmishin is fixing release, wait for tomorrow please, we'll make version 4.6.0 with patch for goreleaser. Thank you!

**Comment by Nmishin** [comment]
@kodachimaru a new version [4.6.2](https://github.com/tofuutils/tenv/releases/tag/v4.6.2) has been released, but I'm not sure that de added some fixes in it.
It looks like more a configuration problem then a bug.

**Comment by kodachimaru** [comment]
@Nmishin , I tried your suggestion of using `TG_INSTALL_MODE="direct"` mode with `TG_REMOTE="https://github.com"` and it worked.

So indeed, seems this is was a configuration issue.
However, I think that the documentation about `TG_REMOTE` should clarify about what to do in case of wanting "direct" Tg install from GH (which, as I said, it's very practical because we avoid GH token maintenance)

**Comment by kvendingoldo** [comment]
>However, I think that the documentation about TG_REMOTE should clarify about what to do in case of wanting "direct" Tg install from GH (which, as I said, it's very practical because we avoid GH token maintenance)

Absolutely agree. @Nmishin can you add it to the documentation when you'll have time, please?

**Comment by Nmishin** [comment]
Fully agree, created the issue for not to forget: https://github.com/tofuutils/tenv/issues/412
